# Generated by Django 3.2.4 on 2021-06-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planter', '0002_auto_20210623_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
